import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPTransport } from '@hono/mcp';
import { z } from 'zod';
import { AStepper, type IHasCycles, type IHasOptions } from '@haibun/core/lib/astepper.js';
import type { TWorld, TStepperStep, TFeatureStep } from '@haibun/core/lib/defs.js';
import { OK, Origin } from '@haibun/core/schema/protocol.js';
import { getFromRuntime, getStepperOption, constructorName, stringOrError } from '@haibun/core/lib/util/index.js';
import { namedInterpolation } from '@haibun/core/lib/namedVars.js';
import { StepperRegistry } from '@haibun/core/lib/stepper-registry.js';
import { currentVersion as version } from '@haibun/core/currentVersion.js';
import { FlowRunner } from '@haibun/core/lib/core/flow-runner.js';
import { FeatureExecutor } from '@haibun/core/phases/Executor.js';
import { DOMAIN_STRING, normalizeDomainKey } from '@haibun/core/lib/domain-types.js';
import type { IWebServer, Context } from './defs.js';
import { WEBSERVER } from './defs.js';

export default class McpStepper extends AStepper implements IHasOptions, IHasCycles {
  options = {
    MCP_PATH: { desc: 'Path for MCP endpoint', parse: (p: string) => stringOrError(p) },
    ACCESS_TOKEN: { desc: 'Access token for MCP auth', parse: (t: string) => stringOrError(t) },
  };

  cycles = {
    startFeature: async () => { await this.setupMcp(); },
    endFeature: async () => { await this.close(); },
  };

  private mcpServer?: McpServer;
  private transport?: StreamableHTTPTransport;
  private steppers: AStepper[] = [];
  private runner?: FlowRunner;
  private mcpPath = '/mcp';
  private accessToken = '';

  async setWorld(world: TWorld, steppers: AStepper[]) {
    await super.setWorld(world, steppers);
    this.steppers = steppers;
    this.runner = new FlowRunner(world, steppers);
    this.mcpPath = (getStepperOption(this, 'MCP_PATH', world.moduleOptions) as string) || '/mcp';
    this.accessToken = (getStepperOption(this, 'ACCESS_TOKEN', world.moduleOptions) as string) || '';
  }

  private async setupMcp() {
    if (this.mcpServer) return; // Idempotent

    const webserver = getFromRuntime(this.getWorld().runtime, WEBSERVER) as IWebServer;
    if (!webserver) throw new Error('McpStepper: No webserver found in runtime.');

    this.mcpServer = new McpServer({ name: 'haibun-mcp', version });

    // Initialize transport
    this.transport = new StreamableHTTPTransport({
      enableJsonResponse: true,
    });

    this.registerStepperTools();

    // Connect the transport to the server instance
    await this.mcpServer.connect(this.transport);

    // --- Middleware: Apply Header Fixes and Auth ---
    const applyMcpMiddleware = async (c: Context, next: () => Promise<void>) => {
      // 1. CORS Headers (Required for MCP Inspector / Web Clients)
      c.header('Access-Control-Allow-Origin', '*');
      c.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
      c.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Accept, X-Custom-Header');

      if (c.req.method === 'OPTIONS') {
        return c.body(null, 204);
      }

      // 2. Auth Logic
      if (this.accessToken) {
        const auth = c.req.header('authorization');
        if (!auth?.startsWith('Bearer ') || auth.slice(7) !== this.accessToken) {
          console.warn(`[MCP] Unauthorized access attempt to ${c.req.path}`);
          return c.json({ error: 'Unauthorized' }, 401);
        }
      }

      // 3. THE FIX: "Gentle" Header Override
      // We do NOT create a new Request() because that consumes the body stream and causes EOF.
      // Instead, we override the header accessor method on this specific context.
      const originalHeader = c.req.header.bind(c.req);

      // @ts-ignore - We are monkey-patching the Hono Request wrapper
      c.req.header = (name?: string) => {
        if (name?.toLowerCase() === 'accept') {
          // StreamableHTTPTransport requires both accept types for POST requests
          if (c.req.method === 'POST') return 'application/json, text/event-stream';
          if (c.req.method === 'GET') return 'text/event-stream';
        }
        return originalHeader(name);
      };

      await next();
    };

    webserver.app.use(this.mcpPath, applyMcpMiddleware);
    webserver.app.use(`${this.mcpPath}/*`, applyMcpMiddleware);

    // --- Route Handler ---
    // Handle both GET (SSE) and POST (Messages) on the same path
    const handleMcpRequest = async (c: Context) => {
      console.log(`[MCP] Handling ${c.req.method} request on ${c.req.path}`);

      // Pass the context to the transport.
      // It will use our patched c.req.header() to validate the request.
      const response = await this.transport!.handleRequest(c);

      if (!response) {
        console.warn('[MCP] No response generated by transport');
        return c.notFound();
      }

      return response;
    };

    webserver.app.all(this.mcpPath, handleMcpRequest);
    webserver.app.all(`${this.mcpPath}/*`, handleMcpRequest);

    this.getWorld().eventLogger.info(`🔗 MCP endpoint registered at ${this.mcpPath}`);
  }

  private registerStepperTools() {
    for (const stepper of this.steppers) {
      const stepperName = constructorName(stepper);
      for (const [stepName, stepDef] of Object.entries(stepper.steps)) {
        if (stepDef.expose === false) continue;

        const variables: Record<string, z.ZodTypeAny> = {};
        if (stepDef.gwta) {
          const { stepValuesMap } = namedInterpolation(stepDef.gwta);
          if (stepValuesMap) {
            for (const v of Object.values(stepValuesMap)) {
              const rawDomain = v.domain || DOMAIN_STRING;
              const parts = rawDomain.split(' | ').sort();
              const domainKey = normalizeDomainKey(parts.join(' | '));
              const domain = this.world.domains[domainKey];
              variables[v.term] = (domain?.schema || z.string()) as any;
            }
          }
        }

        (this.mcpServer! as any).tool(
          `${stepperName}-${stepName}`,
          stepDef.gwta || stepName,
          variables,
          this.createToolHandler(stepperName, stepName, stepDef)
        );
      }
    }
  }

  private createToolHandler(stepperName: string, stepName: string, stepDef: TStepperStep) {
    return async (input: Record<string, unknown>) => {
      console.log(`[MCP] Tool Execution: ${stepperName}-${stepName}`);
      try {
        const featureStep: TFeatureStep = {
          in: stepDef.gwta || '',
          action: {
            stepperName,
            actionName: stepName,
            step: stepDef,
            stepValuesMap: this.mapInputToValues(input, stepDef),
          },
          seqPath: [0],
          source: { path: 'mcp' }
        };

        const result = await FeatureExecutor.doFeatureStep(this.steppers, featureStep, this.world);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        return { content: [{ type: 'text' as const, text: message }], isError: true };
      }
    };
  }

  private mapInputToValues(input: Record<string, unknown>, stepDef: TStepperStep) {
    const { stepValuesMap } = namedInterpolation(stepDef.gwta || '');
    const updatedMap = { ...stepValuesMap };
    for (const [key, val] of Object.entries(input)) {
      if (updatedMap[key]) {
        updatedMap[key] = {
          ...updatedMap[key],
          term: String(val),
          origin: Origin.quoted
        };
      }
    }
    return updatedMap;
  }

  async close() {
    if (this.mcpServer) {
      await this.mcpServer.close();
    }
    this.mcpServer = undefined;
    this.transport = undefined;
  }

  steps = {
    serveMcpTools: {
      gwta: 'serve mcp tools at {path}',
      action: async ({ path }: { path: string }) => {
        this.mcpPath = String(path);
        await this.setupMcp();
        return OK;
      },
    },
  };
}